### ISSUE TITLE
test

### ISSUE THREAD

**Issue by CosignCosine** [CosignCosine/Tucker2#5]
test

**Comment by MatthiasSaihttam** [comment]
You online?

**Comment by CosignCosine** [comment]
Yes, I am online.

**Comment by MatthiasSaihttam** [comment]
Do you mind if I clone this and host it myself? And do you have any advice for how I could do that?

**Comment by CosignCosine** [comment]
You can definitely do that! You'll need to configure a few things in options.js, but other than that it should be perfectly fine and running. Use https://discordapp.com/developers/applications/me to create a new bot, and then use the parameters there to configure the options.js file. :) 

I'm going to set up some actual instructions soon, I'm being stupid and lazy and haven't worked on that yet.

**Comment by MatthiasSaihttam** [comment]
Thanks!

**Comment by CosignCosine** [comment]
You're welcome!
